# Generated by Django 5.1.6 on 2025-02-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_isbn_alter_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies_available',
            field=models.IntegerField(default=2, help_text='Number of copies available'),
        ),
    ]
